name: Publish App

on:
  push:
    branches: [ master ]

jobs:

  publish:

    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Download math result for job build
        uses: actions/download-artifact@v1
        with:
          name: testing
      - name: Release GitHub Actions
        uses: technote-space/release-github-actions@v6