name: Publish App

on:
  push:
    branches:
      - master

jobs:
        
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: nanasess/setup-chromedriver@master
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Maven
      run: mvn clean package

    - name: Verify Sonar
      run: mvn sonar:sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
    - name: Get project version
      id: version
      run: echo "::set-output name=version::$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)"

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: testing
        path: target/enunciado-practica-testing-${{steps.version.outputs.version}}.jar

  publish:

    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Get project version
        id: version
        run: echo "::set-output name=version::$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)"
      
      - name: Download math result for job build
        uses: actions/download-artifact@v1
        with:
          name: testing
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: testing/enunciado-practica-testing-${{steps.version.outputs.version}}.jar
          asset_name: Testing.jar
          tag: ${{steps.version.outputs.version}}
          overwrite: true